---
- name: Create configuration for Leaf/Access Devices
  hosts: leaf
  connection: local
  gather_facts: no
  pre_tasks:
    - include_vars: "{{ topology_file }}"
  roles:
    - junos-system
    - junos-mclag-icl
    - junos-mclag-qfx10k
    - build-config
