---
- name: Generate variables for spine
  hosts: spine
  connection: local
  gather_facts: no
  pre_tasks:
    - include_vars: "{{ topology_file }}"
  vars:
    generate_p2p:
      nbr_networks: 40
      network_size: 31
      network_pool: 172.16.0.0/24
    generate_tenant:
      nbr_tenant: 2
      nbr_vni_tenant: 15
      tenant_start_id: 10
      vlan_start: 100
      vni_prefix: 9
      network_pool: 100.0.0.0/16
      network_size: 24
  roles:
    - generate-p2p-ips
    - generate-tenant-vni

- name: Generate variables for leaf
  hosts: leaf
  connection: local
  gather_facts: no
  pre_tasks:
    - include_vars: "{{ topology_file }}"
  vars:
    vlans_start: 100
    vlans_end: 130
    # ntwk_start: 10.0.0.0/16
    # ntwk_size: 24
  roles:
    - generate_vlans
