
access:
    interfaces:
        -   name: ae0
            mode: trunk
            esi: 00:01:01:01:01:01:01:01:01:01
            vlans: [ 101, 102, 103, 104, 105, 106, 107, 108 ]
            lacp_system_id: 00:00:00:01:01:01
            lacp_mode: active
            description: "customer XX - server YY"

        -   name: ae1
            mode: trunk
            esi: 00:01:01:01:01:02:02:02:02:02
            vlans: [ 101, 102, 103, 104, 105, 106, 107, 108 ]
            lacp_system_id: 00:00:00:02:02:02
            lacp_mode: active
            description: "customer XX - server YY"

## Interfaces to access device
        -   name: "{{ topo[inventory_hostname].port1.name }}"
            description: "{{ topo[inventory_hostname].port3.peer }}"
            mode: aggregate
            parent: ae0
        -   name: "{{ topo[inventory_hostname].port2.name }}"
            description: "{{ topo[inventory_hostname].port3.peer }}"
            mode: aggregate
            parent: ae0
        -   name: "{{ topo[inventory_hostname].port3.name }}"
            description: "{{ topo[inventory_hostname].port5.peer }}"
            mode: aggregate
            parent: ae1
        -   name: "{{ topo[inventory_hostname].port4.name }}"
            description: "{{ topo[inventory_hostname].port6.peer }}"
            mode: aggregate
            parent: ae1
